### ISSUE TITLE
Minimum rich version requirement

### ISSUE THREAD

**Issue by vigji** [FedeClaudi/pyinspect#12]
Specify minimum rich version requirement to prevent
ImportError: cannot import name 'inspect' from 'rich' (C:\Users\lpetrucco\AppData\Roaming\Python\Python37\site-packages\rich\__init__.py)

**Comment by FedeClaudi** [comment]
Will add to the next release (being developed in `dev` branch, thanks!)

**Comment by FedeClaudi** [comment]
Added in [the new release](https://github.com/FedeClaudi/pyinspect/releases/tag/0.0.7)

Thanks @vigji
