### ISSUE TITLE
Release to pypi including requests requirement

### ISSUE THREAD

**Issue by alexmojaki** [FedeClaudi/pyinspect#19]
`import pyinspect` leads to `ModuleNotFoundError: No module named 'requests'`. `requests` is listed in setup.py here but not in the files on https://pypi.org/project/pyinspect/#files

**Comment by FedeClaudi** [comment]
Thanks, will add.

**Comment by FedeClaudi** [comment]
I've released a new version on pypi, hope that works.

**Comment by alexmojaki** [comment]
That did work, but:

1. Why did you commit `__version__ = "0.1.1rc"` but https://pypi.org/project/pyinspect/#history says 0.1.0?
2. Shouldn't you have an automated build or something which would have caught this? Why do you have a static coverage.svg badge?

**Comment by FedeClaudi** [comment]
I like having a development version and only release a proper one when I'm happy with it.  I tend to have an `rc` version on my repository and occasionally, if necessary, publish it to pypi.

I'm not aware of ways to automatically generated the coverage svg?

**Comment by alexmojaki** [comment]
There are free services that help tracking coverage like https://coveralls.io/ - see https://github.com/alexmojaki/executing for an example including a dynamic coverage badge.

However it only makes sense to consider this when you have a working automated build. It looks like you started on GitHub actions, then what happened?

**Comment by FedeClaudi** [comment]
Cool, thank you!

What happened is that I kind of got this package to where I wanted it to be and didn't plan on continuing development on it, so I didn't have a need for something like that. Thanks for the help!
